# vBasic v1.0 by Yochran
# https://github.com/Yochran

# One of the server cores for VectroMC
# https://vectromc.net

# Prefixes:

PluginPrefix: "&7[&6&lvBasic&7]"
ServerPrefix: "&7[&6&lvBasic&7]"

# Permissions:

StaffAlertsPermission: "vbasic.staffalerts"
TeleportPermission: "vbasic.teleport"

# Config Messages:

MustBePlayer: "%plugin_prefix% &cYou must be a player to use that command."
NoPermission: "%server_prefix% &cYou do not have permission to use that command."
InvalidPlayer: "%server_prefix% &cInvalid Player!"

ReloadConfig: "%plugin_prefix% &aYou have successfully reloaded the config.yml."
ReloadPermission: "vbasic.reload"

# Everything regarding /teleport is below:

TeleportIncorrectUsage: "%server_prefix% &cIncorrect Usage! /tp <player> [player]"
TeleportHereIncorrectUsage: "%server_prefix% &cIncorrect Usage! /tphere <player>"
TeleportInvalidPlayer: "%server_prefix% &cInvalid Player!"

# You cannot use server or plugin prefix for these below!
TeleportedToPlayer: "&eYou have teleported to %target%&e."
TeleportedToPlayerNotSender: "&eYou have been teleported to %player%&e."
TeleportPlayerToYou: "&eYou have teleported %target% &eto you."
PlayerTeleportedPlayerToPlayer: "&eYou have been teleported to %target% &eby %player%&e."
YouTeleportedPlayerToPlayer: "&eYou have teleported %target1% &eto &e%target2%&e."
TpAll: "&eYou have teleported &6ALL &eplayers to you."
BackMessage: "&eYou have teleported to your previous location."
BackError: "&eYou have nowhere to teleport back to."

# Everything regarding /broadcast is below:

BroadcastIncorrectUsage: "%server_prefix% &cIncorrect Usage! /bc <message>"
BroadcastFormat: "&7[&6&lALERT&7] &f&l%message%"

# Everything regarding /gamemode is below:

GamemodePermission: "vbasic.gamemode"

GamemodeIncorrectUsage: "%server_prefix% Incorrect Usage! /gamemode <survival/creative/adventure/spectator> [player]"

CreativeSelf: "&eYour gamemode has been set to &6Creative&e."
SurvivalSelf: "&eYour gamemode has been set to &6Survival&e."
SpectatorSelf: "&eYour gamemode has been set to &6Spectator&e."
AdventureSelf: "&eYour gamemode has been set to &6Adventure&e."

CreativeOther: "&eYou have set %target%&e's gamemode to &6Creative&e."
SurvivalOther: "&eYou have set %target%&e's gamemode to &6Survival&e."
SpectatorOther: "&eYou have set %target%&e's gamemode to &6Spectator&e."
AdventureOther: "&eYou have set %target%&e's gamemode to &6Adventure&e."

GamemodeInvalidPlayer: "%server_prefix% &cInvalid Player!"

# Everything relating to heal and feed is below:

HealPermission: "vbasic.heal"
FeedPermission: "vbasic.feed"

HealSelfMsg: "&eYou have been healed."
HealOtherMsg: "&eYou have healed %target%&e."

FeedSelfMsg: "&eYou have been fed."
FeedOtherMsg: "&eYou have fed %target%&e."

HealInvalidPlayer: "%server_prefix% &cInvalid Player!"
FeedInvalidPlayer: "%server_prefix% &cInvalid Player!"

# Everything relating to /msg, /tgc, and /tms is below:

MsgIncorrectUsage: "%server_prefix% &cIncorrect Usage! /msg <player> <message>"
ReplyIncorrectUsage: "%server_prefix% &cIncorrect Usage! /r <message>"
ReplyNotMessaging: "&cYou are not messaging anyone!"

MsgToFormat: "&e(To %target%&e)%message%"
MsgFromFormat: "&e(From %player%&e)%message%"
TpmToError: "&cYou cannot send messages as you have private messages disabled."
TpmFromError: "&cYou cannot send this user messages as they have private messages disabled."
TgcChatError: "&cYou cannot talk in chat as you have global chat disabled."
PlayerNotFound: "&cThat player was not found."

TpmOn: "&aYou have enabled private messages."
TpmOff: "&cYou have disabled private messages."
TmsOn: "&aYou have enabled message sounds."
TmsOff: "&cYou have disabled message sounds."
TgcOn: "&aYou have enabled global chat."
TgcOff: "&cYou have disabled global chat."

# Everything regarding the spawn is below:

SpawnEveryJoin: false

Spawn:
  X: 0.5
  Y: 60
  Z: 0.5
  World: world
  Pitch: 0.0
  Yaw: 0.1

# Everything relating to /fly is below:

FlyPermission: "vbasic.fly"
FlyIncorrectUsage: "%server_prefix% &cIncorrect Usage! /fly [player]"
FlyInvalidPlayer: "%server_prefix% &cInvalid Player!"
FlyTargetOn: "&eYour fly mode has been &6enabled&e."
FlyTargetOff: "&eYour fly mode has been &6disabled&e."
FlyPlayerOn: "&eYou have set %player%&e's fly mode to &6true&e."
FlyPlayerOff: "&eYou have set %player%&e's fly mode to &6false&e."

# Everything relating to /speed is below:

SpeedPermission: "vbasic.speed"
SpeedInvalidSpeed: "%server_prefix% &cInvalid Speed! Speed must be between -1 and 1."
SpeedIncorrectUsage: "%server_prefix% &cIncorrect Usage! /speed <amount> [player]"
SpeedInvalidPlayer: "%server_prefix% &cInvalid Player!"
SpeedPlayerSet: "&eYou have set %player%&e's speed to &6%speed%&e."
SpeedTargetSet: "&eYour speed has been set to &6%speed%&e."

# Everything relating to /seen is below:

SeenPermission: "vbasic.seen"
SeenIPViewPermission: "vbasic.seen.ip"
SeenIncorrectUsage: "%server_prefix% &cIncorrect Usage! /seen <player>"
SeenInvalidPlayer: "%server_prefix% &cInvalid Player!"
SeenHiddenIP: "&6(IP Hidden)"
SeenFormat: |-
  &7&m------------------------
  %player%&6's user-info:
  &e -
  &eFirst Joined: &6%firstjoin%
  &eIP: &6%ip%
  &eRank: %rank%
  &7&m------------------------

# Staff Alerts for everything are below:

StaffAlerts:
  # You cannot use server or plugin prefix for these below!
  ToggleOnMessage: "&eYou have toggled &6on &estaff alerts."
  ToggleOffMessage: "&eYou have toggled &6off &estaff alerts."
  TeleportToPlayer: "&7&o[%player% &7&oteleported to %target%&7&o]"
  TeleportHerePlayer: "&7&o[%player% &7&oteleported %target% &7&oto themselves]"
  PlayerTeleportedPlayerToPlayer: "&7&o[%player% &7&oteleported %target1% &7&oto %target2%&7&o]"
  TpAll: "&7&o[%player% &7&oteleported all players to themself]"
  Broadcast: "&7&o[%player% &7&obroadcasted: &e&o%message%&7&o]"
  HealSelf: "&7&o[%player% &7&ohas healed themselves&7&o]"
  HealOther: "&7&o[%player% &7&ohas healed %target%&7&o]"
  FeedSelf: "&7&o[%player% &7&ohas fed themselves&7&o]"
  FeedOther: "&7&o[%player% &7&ohas fed %target%&7&o]"
  Back: "&7&o[%player% &7&ohas teleported to their previous location]"
