# vBasic v1.0 by Yochran
# https://github.com/Yochran

# One of the server cores for VectroMC
# https://vectromc.net

# Prefixes:

PluginPrefix: "&7[&6&lvBasic&7]"
ServerPrefix: "&7[&6&lvBasic&7]"

# Permissions:

StaffAlertsPermission: "vbasic.staffalerts"
TeleportPermission: "vbasic.teleport"

# Config Messages:

MustBePlayer: "%plugin_prefix% &cYou must be a player to use that command."
NoPermission: "%server_prefix% &cYou do not have permission to use that command."
InvalidPlayer: "%server_prefix% &cInvalid Player!"

ReloadConfig: "%plugin_prefix% &aYou have successfully reloaded the config.yml."
ReloadPermission: "vbasic.reload"

# Death Messages

DeathMessages: false

# Everything regarding /teleport is below:

TeleportIncorrectUsage: "%server_prefix% &cIncorrect Usage! /tp <player> [player]"
TeleportHereIncorrectUsage: "%server_prefix% &cIncorrect Usage! /tphere <player>"
TeleportInvalidPlayer: "%server_prefix% &cInvalid Player!"

# You cannot use server or plugin prefix for these below!
TeleportedToPlayer: "&eYou have teleported to %target%&e."
TeleportedToPlayerNotSender: "&eYou have been teleported to %player%&e."
TeleportPlayerToYou: "&eYou have teleported %target% &eto you."
PlayerTeleportedPlayerToPlayer: "&eYou have been teleported to %target% &eby %player%&e."
YouTeleportedPlayerToPlayer: "&eYou have teleported %target1% &eto &e%target2%&e."
TpAll: "&eYou have teleported &6ALL &eplayers to you."
BackMessage: "&eYou have teleported to your previous location."
BackError: "&eYou have nowhere to teleport back to."

# Everything regarding /broadcast is below:

BroadcastIncorrectUsage: "%server_prefix% &cIncorrect Usage! /bc <message>"
BroadcastFormat: "&7[&6&lALERT&7] &f&l%message%"

# Everything regarding /gamemode is below:

GamemodePermission: "vbasic.gamemode"

GamemodeIncorrectUsage: "%server_prefix% Incorrect Usage! /gamemode <survival/creative/adventure/spectator> [player]"

CreativeSelf: "&eYour gamemode has been set to &6Creative&e."
SurvivalSelf: "&eYour gamemode has been set to &6Survival&e."
SpectatorSelf: "&eYour gamemode has been set to &6Spectator&e."
AdventureSelf: "&eYour gamemode has been set to &6Adventure&e."

CreativeOther: "&eYou have set %target%&e's gamemode to &6Creative&e."
SurvivalOther: "&eYou have set %target%&e's gamemode to &6Survival&e."
SpectatorOther: "&eYou have set %target%&e's gamemode to &6Spectator&e."
AdventureOther: "&eYou have set %target%&e's gamemode to &6Adventure&e."

GamemodeInvalidPlayer: "%server_prefix% &cInvalid Player!"

# Everything relating to heal and feed is below:

HealPermission: "vbasic.heal"
FeedPermission: "vbasic.feed"

HealSelfMsg: "&eYou have been healed."
HealOtherMsg: "&eYou have healed %target%&e."

FeedSelfMsg: "&eYou have been fed."
FeedOtherMsg: "&eYou have fed %target%&e."

HealInvalidPlayer: "%server_prefix% &cInvalid Player!"
FeedInvalidPlayer: "%server_prefix% &cInvalid Player!"

# Everything relating to /clear is below:

ClearPermission: "vbasic.clear"
ClearIncorrectUsage: "%server_prefix% &cIncorrect Usage! /clear [player]"
ClearInvalidPlayer: "%server_prefix% &cInvalid Player!"
ClearMsg: "&eCleared all items from %player%&e."

# Everything relating to /itemname is below:

ItemNamePermission: "vbasic.iname"
ItemNameIncorrectUsage: "%server_prefix% &cIncorrect Usage! /iname <name>"
ItemNameInvalidItem: "%server_prefix% &cInvalid Item!"
ItemNameMsg: "&eYou have set the name of your current item to &6%name%&e."

# Everything relating to /msg, /tgc, and /tms is below:

MsgIncorrectUsage: "%server_prefix% &cIncorrect Usage! /msg <player> <message>"
ReplyIncorrectUsage: "%server_prefix% &cIncorrect Usage! /r <message>"
ReplyNotMessaging: "&cYou are not messaging anyone!"

MsgToFormat: "&e(To %target%&e)%message%"
MsgFromFormat: "&e(From %player%&e)%message%"
TpmToError: "&cYou cannot send messages as you have private messages disabled."
TpmFromError: "&cYou cannot send this user messages as they have private messages disabled."
TgcChatError: "&cYou cannot talk in chat as you have global chat disabled."
PlayerNotFound: "&cThat player was not found."

TpmOn: "&aYou have enabled private messages."
TpmOff: "&cYou have disabled private messages."
TmsOn: "&aYou have enabled message sounds."
TmsOff: "&cYou have disabled message sounds."
TgcOn: "&aYou have enabled global chat."
TgcOff: "&cYou have disabled global chat."

# Everything relating to /fly is below:

FlyPermission: "vbasic.fly"
FlyIncorrectUsage: "%server_prefix% &cIncorrect Usage! /fly [player]"
FlyInvalidPlayer: "%server_prefix% &cInvalid Player!"
FlyTargetOn: "&eYour fly mode has been &6enabled&e."
FlyTargetOff: "&eYour fly mode has been &6disabled&e."
FlyPlayerOn: "&eYou have set %player%&e's fly mode to &6true&e."
FlyPlayerOff: "&eYou have set %player%&e's fly mode to &6false&e."

# Everything relating to /speed is below:

SpeedPermission: "vbasic.speed"
SpeedInvalidSpeed: "%server_prefix% &cInvalid Speed! Speed must be between -1 and 1."
SpeedIncorrectUsage: "%server_prefix% &cIncorrect Usage! /speed <amount> [player]"
SpeedInvalidPlayer: "%server_prefix% &cInvalid Player!"
SpeedPlayerSet: "&eYou have set %player%&e's speed to &6%speed%&e."
SpeedTargetSet: "&eYour speed has been set to &6%speed%&e."

# Everything relating to /seen is below:

SeenPermission: "vbasic.seen"
SeenIPViewPermission: "vbasic.seen.ip"
SeenIncorrectUsage: "%server_prefix% &cIncorrect Usage! /seen <player>"
SeenInvalidPlayer: "%server_prefix% &cInvalid Player!"
SeenHiddenIP: "&6(IP Hidden)"
SeenFormat: |-
  &7&m------------------------
  %player%&6's user-info:
  &e -
  &eFirst Joined: &6%firstjoin%
  &eIP: &6%ip%
  &eRank: %rank%
  &7&m------------------------

# Everything below is for the fun commands.

Hat:
  Permission: "vbasic.hat"
  InvalidItem: "%server_prefix% &cInvalid Item!"
  Message: "&eYou have set your hat."

# Everything below is for sudo command.

Sudo:
  Permission: "vbasic.sudo"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /sudo <player> <command/message>"
  InvalidPlayer: "%server_prefix% &cInvalid Player!"
  Format: "&eYou have sudod %player% &eto run &6%sudo%&e."

# Everything below is relating to the economy:

Economy:
  EnabledWorlds:
    - kitpvp
    - soup
    - survival
  StartingAmount: 0.00
  # Warning: Going over this maximum amount will cause the plugin to break. In future version,
  # it will be able to be more than this.
  MaximumAmount: 999999999999999
  MoneyPerKill:
    EnabledWorlds:
      - kitpvp
      - soup
    Highest: 20.5
    Lowest: 12.5
  MoneyOnKillMessage: "&eYou have killed %player% &efor &6$%amount%&e."
  NotEnabledMessage: "%server_prefix% &cThe economy is not enabled."
  # Economy Command
  Command:
    Permission: "vbasic.economy.command"
    IncorrectUsage: "%server_prefix% &cIncorrect Usage! /eco <set/give/take/reset> <player> [amount]"
    InvalidPlayer: "%server_prefix% &cInvalid Player!"
    InvalidAmount: "%server_prefix% &cInvalid Amount! Must be less than %maximum%."
    Format:
      Set: "&eYou have set %player%&e's balance to &6$%amount%&e."
      Give: "&eYou have added &6$%amount% &eto %player%&e's balance."
      Take: "&eYou have removed &6$%amount% &efrom %player%&e's balance."
      Reset: "&eYou have reset %player%&e's balance to &6$%amount%&e."
    FormatTarget: "&eYour balance has been set to &6$%balance%&e."

Balance:
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /bal <player>"
  InvalidPlayer: "%server_prefix% &cInvalid Player!"
  Format: "%player%&e's balance: &6$%balance%&e."

Pay:
  MinimumAmount: 1
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /pay <player> <amount>"
  InvalidPlayer: "%server_prefix% &cInvalid Player!"
  InvalidAmount: "%server_prefix% &cInvalid Amount! Must be at least $%minimum%, must be less than $%maximum%."
  NotEnoughMoney: "%server_prefix% &cYou don't have enough money for that."
  FormatSender: "&eYou have paid %player% &6$%amount%&e."
  FormatTarget: "&eYou have been sent &6$%amount% &efrom %player%&e."

Bounty:
  EnabledWorlds:
    - kitpvp
    - soup
  NotEnabledMessage: "%server_prefix% &cBounty is not enabled."
  MinimumAmount: 100
  RemoveFee: 1000
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /bounty <player> <amount>"
  InvalidPlayer: "%server_prefix% &cInvalid Player!"
  InvalidAmount: "%server_prefix% &cInvalid Amount! Must be more than $%minimum%, must be less than $%maximum%!"
  NotEnoughMoney: "%server_prefix% &cYou don't have enough money for that."
  Format: "&eYou have placed a bounty on %player% &efor &6$%amount%&e."
  FormatIncreased: "&eYou have increased the bounty on %player% &eto &6$%amount%&e."
  Broadcast: "%player% &ehas placed a &6$%amount% &ebounty on %target%&e!\n&eKill them to receive this money."
  BroadcastIncreased: "%player% &ehas increased then bounty on %target% &eto &6$%amount%&e!\n&eKill them to receive this money."
  Completed: "%player% &ehas killed %target% &eand claimed a &6$%amount% &ebounty!"

Unbounty:
  Permission: "vbasic.unbounty"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /unbounty <player>"
  InvalidPlayer: "%server_prefix% &cInvalid Player!"
  PlayerNotBountied: "%server_prefix% &cPlayer is not bountied!"
  Format: "&eYou have removed the &6$%amount% &ebounty on %player%&e."

# Everything below is relating to player stats.

Stats:
  EnabledWorlds:
    - kitpvp
    - soup
  NotEnabledMessage: "%server_prefix% &cStats are not enabled."
  MinimumStreakEndBroadcast: 10
  StreakEndBroadcast: "&6&l<!> %player% &ehas ended %target%&e's &6%streak% &ekillstreak. &6&l<!>"
  Command:
    IncorrectUsage: "%server_prefix% &cIncorrect Usage! /stats [player]"
    InvalidPlayer: "%server_prefix% &cInvalid Player!"
    Format: |-
      &7&m-----------------------
      %player%&e's Stats:
      &7- -
      &eKills: &6%kills%
      &eDeaths: &6%deaths%
      &eKDR: &6%kdr%
      &eStreak: &6%streak%
      &7&m-----------------------

ResetStats:
  Permission: "vbasic.resetstats"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /resetstats <player>"
  InvalidPlayer: "%server_prefix% &cInvalid Player!"
  Format: "&eYou have successfully reset %player%&e's &6stats&e."

# Staff Alerts for everything are below:

StaffAlerts:
  # You cannot use server or plugin prefix for these below!
  ToggleOnMessage: "&eYou have toggled &6on &estaff alerts."
  ToggleOffMessage: "&eYou have toggled &6off &estaff alerts."
  TeleportToPlayer: "&7&o[%player% &7&oteleported to %target%&7&o]"
  TeleportHerePlayer: "&7&o[%player% &7&oteleported %target% &7&oto themselves]"
  PlayerTeleportedPlayerToPlayer: "&7&o[%player% &7&oteleported %target1% &7&oto %target2%&7&o]"
  TpAll: "&7&o[%player% &7&oteleported all players to themself]"
  Broadcast: "&7&o[%player% &7&obroadcasted: &e&o%message%&7&o]"
  HealSelf: "&7&o[%player% &7&ohas healed themselves&7&o]"
  HealOther: "&7&o[%player% &7&ohas healed %target%&7&o]"
  FeedSelf: "&7&o[%player% &7&ohas fed themselves&7&o]"
  FeedOther: "&7&o[%player% &7&ohas fed %target%&7&o]"
  Back: "&7&o[%player% &7&ohas teleported to their previous location]"
  Sudo: "&7&o[%player% &7&ohas sudod %target% &7&oto run: &e&o%sudo%&7&o]"
