# vNitrogen v1.0 by Yochran
# https://github.com/Yochran

# One of the server cores for VectroMC
# https://vectromc.net

# Prefixes:

PluginPrefix: "&7[&6&lvNitrogen&7]"
ServerPrefix: "&7[&6&lVectroMC&7]"

# Ranks:

Console:
  name: "&c&lConsole"

# RANK NAMES MUST BE UPPERCASE!!!!

Ranks:
  OWNER:
    default: false
    name: "Owner"
    prefix: "&7(&4Owner&7) &4"
    color: "&4"
    display: "&4Owner"
    grantItem: "RED_WOOL"
    permission: "vnitrogen.groups.owner"
  DEVELOPER:
    default: false
    name: "Developer"
    prefix: "&7(&6&oDeveloper&7) &6&o"
    color: "&6&o"
    display: "&6&oDeveloper"
    grantItem: "ORANGE_WOOL"
    permission: "vnitrogen.groups.developer"
  MANAGER:
    default: false
    name: "Manager"
    prefix: "&7(&9Manager&7) &9"
    color: "&9"
    display: "&9Manager"
    grantItem: "BLUE_WOOL"
    permission: "vnitrogen.groups.manager"
  ADMIN:
    default: false
    name: "Admin"
    prefix: "&7(&cAdmin&7) &c"
    color: "&c"
    display: "&cAdmin"
    grantItem: "RED_WOOL"
    permission: "vnitrogen.groups.admin"
  SENIOR-MOD:
    default: false
    name: "Senior-Mod"
    prefix: "&7(&5&oSenior-Mod&7) &5&o"
    color: "&5&o"
    display: "&5&oSenior-Mod"
    grantItem: "PURPLE_WOOL"
    permission: "vnitrogen.groups.seniormod"
  MOD:
    default: false
    name: "Mod"
    prefix: "&7(&5Mod&7) &5"
    color: "&5"
    display: "&5Mod"
    grantItem: "PURPLE_WOOL"
    permission: "vnitrogen.groups.mod"
  TRIAL-MOD:
    default: false
    name: "Trial-Mod"
    prefix: "&7(&eTrial-Mod&7) &e"
    color: "&e"
    display: "&eTrial-Mod"
    grantItem: "YELLOW_WOOL"
    permission: "vnitrogen.groups.trialmod"
  BUILDER:
    default: false
    name: "Builder"
    prefix: "&7(&2Builder&7) &2"
    color: "&2"
    display: "&2Builder"
    grantItem: "GREEN_WOOL"
    permission: "vnitrogen.groups.builder"
  DEFAULT:
    default: true
    name: "Default"
    prefix: "&7"
    color: "&7"
    display: "&7Default"
    grantItem: "GRAY_WOOL"
    permission: "vnitrogen.groups.default"

# Config Messages:

YouMustBePlayer: "%plugin_prefix% &cYou must be a player to use that command."
NoPermission: "%server_prefix% &cYou do not have permission to use that command."
CantFindPlayer: "%server_prefix% &cThat player was not found."
ReloadConfig: "%plugin_prefix% &aYou have successfully reloaded the config.yml, and the playerdata.yml."

# Everything regarding to the /setrank command:

Setrank:
  CommandToRun: "pex user %player% group set %rank%"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /setrank <player> <rank>"
  InvalidRank: "%server_prefix% &cInvalid Rank!"
  SenderSetRank: "&aYou have set %target%&a's rank to %rank%&a."
  TargetSetRank: "&aYour rank has been set to %rank%&a."

# Everything regarding to the /grant command:

Grant:
  Permission: "vnitrogen.grant"
  InvalidPlayer: "%server_prefix% &cInvalid Player!"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /grant <player>"
  GrantMenu:
    Lore:
      - "&7&m----------------------------------"
      - "&eGrant the %rank% &erank to %player%&e."
      - "&e "
      - "&eClicking this option will set"
      - "%player%&e's rank to %rank%&e."
      - "&7&m----------------------------------&r"
  DurationMenu:
    Items:
      TenSeconds:
        Item: "WHITE_WOOL"
        Name: "&f10 Seconds"
        ID: "10 Seconds"
        Slot: 10
      OneMinute:
        Item: "YELLOW_WOOL"
        Name: "&e1 Minute"
        ID: "1 Minute"
        Slot: 11
      FiveMinutes:
        Item: "ORANGE_WOOL"
        Name: "&65 Minutes"
        ID: "5 Minutes"
        Slot: 12
      ThirtyMinutes:
        Item: "RED_WOOL"
        Name: "&c30 Minutes"
        ID: "30 Minutes"
        Slot: 13
      OneHour:
        Item: "GREEN_WOOL"
        Name: "&21 Hour"
        ID: "1 Hour"
        Slot: 14
      ThreeHours:
        Item: "LIME_WOOL"
        Name: "&a3 Hours"
        ID: "3 Hours"
        Slot: 15
      OneDay:
        Item: "BLUE_WOOL"
        Name: "&91 Day"
        ID: "1 Day"
        Slot: 16
      OneWeek:
        Item: "CYAN_WOOL"
        Name: "&31 Week"
        ID: "1 Week"
        Slot: 20
      OneMonth:
        Item: "LIGHT_BLUE_WOOL"
        Name: "&b1 Month"
        ID: "1 Month"
        Slot: 21
      OneYear:
        Item: "PURPLE_WOOL"
        Name: "&51 Year"
        ID: "1 Year"
        Slot: 23
      Permanent:
        Item: "BEDROCK"
        Name: "&8Permanent"
        ID: "Permanent"
        Slot: 24
    Lore:
      - "&7&m----------------------------------"
      - "&eThis grant will last for &6%time%&e."
      - "&e "
      - "&eClicking this option will set"
      - "&ethis grant for %player%"
      - "&eto expire in &6%time%&e."
      - "&7&m----------------------------------"
  ReasonMenu:
    Items:
      NoReason:
        Item: "BEDROCK"
        Name: "&8No Reason"
        ID: "No Reason"
        Slot: 10
      Promoted:
        Item: "LIME_WOOL"
        Name: "&aPromoted"
        ID: "Promoted"
        Slot: 11
      Demoted:
        Item: "RED_WOOL"
        Name: "&cDemoted"
        ID: "Demoted"
        Slot: 12
      Famous:
        Item: "PINK_WOOL"
        Name: "&dFamous"
        ID: "Famous"
        Slot: 13
      Whitelisted:
        Item: "WHITE_WOOL"
        Name: "&fWhitelisted"
        ID: "Whitelisted"
        Slot: 14
      Testing:
        Item: "CYAN_WOOL"
        Name: "&3Testing"
        ID: "Testing"
        Slot: 15
      Custom:
        Item: "OAK_SIGN"
        Name: "&2Custom Reason"
        ID: "Custom Reason"
        Slot: 16
    Lore:
      - "&7&m----------------------------------"
      - "&eThis grant's reason is &6%reason%&e."
      - "&e "
      - "&eClicking this option will set"
      - "&e%player%&e's grant's reason"
      - "&eto &6%reason%&e."
      - "&7&m----------------------------------"
  ConfirmationMenu:
    Lore:
      - "&7&m----------------------------------"
      - "&6&lDetails:"
      - "&e "
      - "&eTarget: &6%player%"
      - "&eRank: &6%rank%"
      - "&eDuration: &6%duration%"
      - "&eReason: &6%reason%"
      - "&7&m----------------------------------"
  CancelledGrant: "&c&lGrant has been cancelled."
  ConfirmedGrant: |-
    &a&lGrant has been confirmed.
    &eGranted User: %player%
    &eGranted Rank: &6%rank%
    &eGrant Duration: &6%duration%
    &eGrant Reason: &6%reason%
  CustomReasonChatMessage: "&ePlease type a &6custom &ereason in chat."

# Everything below is regarding the /grants command and the /ungrant command:

Grants:
  Permission: "vnitrogen.grants"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /grants <player>"

Ungrant:
  Permission: "vnitrogen.grant"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /ungrant <player> <id>"
  InvalidPlayer: "%server_prefix% &cInvalid Player!"
  InvalidGrant: "%server_prefix% &cInvalid Grant!"
  RevokedMessage: "&eSuccessfully revoked grant &6%id% &eof %player%&e."

# Everything regarding the different staff chats:

BuildChat:
  permission: "vnitrogen.chats.build"
  format: "&2[B] &3[%world%] %player%&7: &b%message%"
  incorrectusage: "%server_prefix% &cIncorrect Usage! /bc <message>"
  Toggles:
    ToggleOn: "&2[B] &3You have toggled on &2Build &3chat."
    ToggleOff: "&2[B] &3You have toggled off &2Build &3chat."

StaffChat:
  permission: "vnitrogen.chats.staff"
  format: "&b[S] &3[%world%] %player%&7: &b%message%"
  incorrectusage: "%server_prefix% &cIncorrect Usage! /sc <message>"
  Toggles:
    ToggleOn: "&b[S] &3You have toggled on &bStaff &3chat."
    ToggleOff: "&b[S] &3You have toggled off &bStaff &3chat."

AdminChat:
  permission: "vnitrogen.chats.admin"
  format: "&c[A] &3[%world%] %player%&7: &b%message%"
  incorrectusage: "%server_prefix% &cIncorrect Usage! /ac <message>"
  Toggles:
    ToggleOn: "&c[A] &3You have toggled on &cAdmin &3chat."
    ToggleOff: "&c[A] &3You have toggled off &cAdmin &3chat."

ManagementChat:
  permission: "vnitrogen.chats.management"
  format: "&4[M] &3[%world%] %player%&7: &b%message%"
  incorrectusage: "%server_prefix% &cIncorrect Usage! /mc <message>"
  Toggles:
    ToggleOn: "&4[M] &3You have toggled on &4Management &3chat."
    ToggleOff: "&4[M] &3You have toggled off &4Management &3chat."

# Below is everything regarding staff log messages:

StaffLogin:
  format: "&b[S] %player% &3connected to &b%world%"
  permission: "vnitrogen.staff.log"
  notifypermission: "vnitrogen.notify"
StaffLogout:
  format: "&b[S] %player% &3disconnected from &b%world%"
  permission: "vnitrogen.staff.log"
  notifypermission: "vnitrogen.notify"
StaffWorldChange:
  format: "&b[S] %player% &3connected to &b%newWorld% &3from &b%oldWorld%"
  permission: "vnitrogen.staff.log"
  notifypermission: "vnitrogen.notify"

# Below is everything regarding punishments.

Silent:
  Notify: "vnitrogen.notify.silent"
  Prefix: "&7(Silent)"

History:
  Permission: "vnitrogen.history"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /c <player>"
  InvalidPlayer: "%server_prefix% &cInvalid Player"

Warn:
  Permission: "vnitrogen.warn"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /warn <player> [-s] <reason>"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  GlobalMessage: "%executor% &ahas warned %target%&a."
  ExecutorResponse: "&aYou have warned %player% &afor&f%reason%&a."
  TargetResponse: |-
    &cYou have been warned for&7%reason%&c.
    &4Please stop breaking the rules.

Mute:
  Permission: "vnitrogen.mute"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /mute <player> [-s] <reason>"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  PlayerIsMuted: "%server_prefix% &cPlayer is already muted!"
  GlobalMessage: "%executor% &ahas permanently muted %target%&a."
  ExecutorResponse: "&aYou have permanently muted %player% &afor&f%reason%&a."
  TargetResponse: |-
    &cYou have been permanently muted for&7%reason%&c.
    &4This mute will not expire.
  OnChatError: |-
    &cYou cannot talk as you are muted for&7%reason%&c.
    &4This mute will not expire.

TempMute:
  Permission: "vnitrogen.mute"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /tempmute <player> <time> [-s] <reason>"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  PlayerIsMuted: "%server_prefix% &cPlayer is already muted!"
  GlobalMessage: "%executor% &ahas temporarily muted %target%&a."
  ExecutorResponse: "&aYou have temporarily muted %player% &afor&f%reason%&a."
  TargetResponse: |-
    &cYou have been temporarily muted for&7%reason%&c.
    &cThis mute expires in: &7%expiry%&c.
  OnChatError: |-
    &cYou cannot talk as you are muted for&7%reason%&c.
    &cThis mute expires in: &7%expiry%&c.

Unmute:
  Permission: "vnitrogen.unmute"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /unmute <player> [-s]"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  PlayerIsNotMuted: "%server_prefix% &cPlayer is not muted!"
  GlobalMessage: "%executor% &ahas unmuted %target%&a."
  ExecutorResponse: "&aYou have unmuted %player%&a."
  TargetResponse: "&aYou have been unmuted."

Kick:
  Permission: "vnitrogen.kick"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /kick <player> [-s] <reason>"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  GlobalMessage: "%executor% &ahas kicked %target%&a."
  ExecutorResponse: "&aYou have kicked %player%&a for&f%reason%&a."
  KickMessage: |-
    &cYou have been &4kicked &cfrom the server.
    &7You were kicked for:&f%reason%&7.

Ban:
  Permission: "vnitrogen.ban"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /ban <player> [-s] <reason>"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  GlobalMessage: "%executor% &ahas permanently banned %target%&a."
  ExecutorResponse: "&aYou have permanently banned %player%&a for&f%reason%&a."
  BanMessage: |-
    &cYou have been &4banned &cfrom the server.
    &7You were banned for:&f%reason%&7.
    &4This ban will not expire.

TempBan:
  Permission: "vnitrogen.tempban"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /tempban <player> <time> [-s] <reason>"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  GlobalMessage: "%executor% &ahas temporarily banned %target%&a."
  ExecutorResponse: "&aYou have temporarily banned %player%&a for&f%reason%&a."
  BanMessage: |-
    &cYou have been &4banned &cfrom the server.
    &7You were banned for:&f%reason%&7.
    &cThis ban will expire on: &7%expiry%&c.

Unban:
  Permission: "vnitrogen.unban"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /unban <player> [-s]"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  PlayerIsNotBanned: "%server_prefix% &cPlayer is not banned!"
  GlobalMessage: "%executor% &ahas unbanned %target%&a."
  ExecutorResponse: "&aYou have unbanned %player%&a."

Blacklist:
  Permission: "vnitrogen.blacklist"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /blacklist <player> [-s] <reason>"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  GlobalMessage: "%executor% &ahas permanently blacklisted %target%&a."
  ExecutorResponse: "&aYou have permanently blacklisted %player%&a for&f%reason%&a."
  CantBlacklist: "%server_prefix% &cYou cannot blacklist a player who's never joined."
  BlacklistMessage: |-
    &cYou have been &4blacklisted &cfrom the server.
    &7You were blacklisted for:&f%reason%&7.
    &4This blacklist will not expire.

Unblacklist:
  Permission: "vnitrogen.unblacklist"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /unblacklist <player> [-s]"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  PlayerIsNotBlacklisted: "%server_prefix% &cPlayer is not blacklisted!"
  GlobalMessage: "%executor% &ahas unblacklisted %target%&a."
  ExecutorResponse: "&aYou have unblacklisted %player%&a."

Alts:
  Permission: "vnitrogen.alts"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /alts <player>"
  InvalidPlayer: "%server_prefix% &cInvalid Player!"
  JoinMessageDetected: |-
    &c[A] %player% &3joined, &b%amount% &3alts were detected! &7(/alts %player%&7)
  CommandMessage: "&3Alt Accounts of %player% &7(&4Blacklisted&7, &cBanned&7, &6Muted&7, &aOnline&7, &7Offline&7): %alts%"

MuteChat:
  Permission: "vnitrogen.mutechat"
  Bypass: "vnitrogen.mutechat.bypass"
  GlobalMessageOn: "%player% &ahas muted the &2server chat&a."
  GlobalMessageOff: "%player% &ahas unmuted the &2server chat&a."
  StaffMessageOn: "&b[S] &3[%world%] %player% &3has &bmuted &3the server chat."
  StaffMessageOff: "&b[S] &3[%world%] %player% &3has &bunmuted &3the server chat."
  ChatError: "&cYou cannot talk as the chat is muted."

ClearChat:
  Permission: "vnitrogen.clearchat"
  NotifyPermission: "vnitrogen.clearchat.notify"
  GlobalMessage: "%player% &ahas cleared the &2server chat&a."
  StaffMessage: "&b[S] &3[%world%] %player% &3has &bcleared &3the server chat."
