# vNitrogen v1.0 by Yochran
# https://github.com/Yochran

# One of the server cores for VectroMC
# https://vectromc.net

# Prefixes:

PluginPrefix: "&7[&6&lvNitrogen&7]"
ServerPrefix: "&7[&6&lVectroMC&7]"

# Ranks:

Console:
  name: "&c&lConsole"

Owner:
  prefix: "&7(&4Owner&7) &4"
  color: "&4"
Developer:
  prefix: "&7(&6&oDeveloper&7) &6&o"
  color: "&6&o"
Manager:
  prefix: "&7(&9Manager&7) &9"
  color: "&9"
Admin:
  prefix: "&7(&cAdmin&7) &c"
  color: "&c"
Senior-Mod:
  prefix: "&7(&5&oSenior-Mod&7) &5&o"
  color: "&5&o"
Mod:
  prefix: "&7(&5Mod&7) &5"
  color: "&5"
Trial-Mod:
  prefix: "&7(&eTrial-Mod&7) &e"
  color: "&e"
Builder:
  prefix: "&7(&2Builder&7) &2"
  color: "&2"
Default:
  prefix: "&7"
  color: "&7"

# Config Messages:

YouMustBePlayer: "%plugin_prefix% &cYou must be a player to use that command."
NoPermission: "%server_prefix% &cYou do not have permission to use that command."
CantFindPlayer: "%server_prefix% &cThat player was not found."
ReloadConfig: "%plugin_prefix% &aYou have successfully reloaded the config.yml."

# Everything regarding to the /setrank command:

Setrank:
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /setrank <player> <rank>"
  InvalidRank: "%server_prefix% &cInvalid Rank!"
  # You cannot use %server_prefix% or %plugin_prefix% for these messages below!
  SenderSetRank: "&aYou have set %target%&a's rank to %rank%&a."
  TargetSetRank: "&aYour rank has been set to %rank%&a."

# Everything regarding the different staff chats:

BuildChat:
  permission: "vnitrogen.chats.build"
  format: "&2[B] &3[%world%] %player%&7: &b%message%"
  incorrectusage: "%server_prefix% &cIncorrect Usage! /bc <message>"
  Toggles:
    ToggleOn: "&2[B] &3You have toggled on &2Build &3chat."
    ToggleOff: "&2[B] &3You have toggled off &2Build &3chat."

StaffChat:
  permission: "vnitrogen.chats.staff"
  format: "&b[S] &3[%world%] %player%&7: &b%message%"
  incorrectusage: "%server_prefix% &cIncorrect Usage! /sc <message>"
  Toggles:
    ToggleOn: "&b[S] &3You have toggled on &bStaff &3chat."
    ToggleOff: "&b[S] &3You have toggled off &bStaff &3chat."

AdminChat:
  permission: "vnitrogen.chats.admin"
  format: "&c[A] &3[%world%] %player%&7: &b%message%"
  incorrectusage: "%server_prefix% &cIncorrect Usage! /ac <message>"
  Toggles:
    ToggleOn: "&c[A] &3You have toggled on &cAdmin &3chat."
    ToggleOff: "&c[A] &3You have toggled off &cAdmin &3chat."

ManagementChat:
  permission: "vnitrogen.chats.management"
  format: "&4[M] &3[%world%] %player%&7: &b%message%"
  incorrectusage: "%server_prefix% &cIncorrect Usage! /mc <message>"
  Toggles:
    ToggleOn: "&4[M] &3You have toggled on &4Management &3chat."
    ToggleOff: "&4[M] &3You have toggled off &4Management &3chat."

# Below is everything regarding staff log messages:

StaffLogin:
  format: "&b[S] %player% &3connected to &b%world%"
  permission: "vnitrogen.staff.log"
  notifypermission: "vnitrogen.notify"
StaffLogout:
  format: "&b[S] %player% &3disconnected from &b%world%"
  permission: "vnitrogen.staff.log"
  notifypermission: "vnitrogen.notify"
StaffWorldChange:
  format: "&b[S] %player% &3connected to &b%newWorld% &3from &b%oldWorld%"
  permission: "vnitrogen.staff.log"
  notifypermission: "vnitrogen.notify"

# Below is everything regarding punishments.

Silent:
  Notify: "vnitrogen.notify.silent"
  Prefix: "&7(Silent)"

History:
  Permission: "vnitrogen.history"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /c <player>"
  InvalidPlayer: "%server_prefix% &cInvalid Player"

Warn:
  Permission: "vnitrogen.warn"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /warn <player> [-s] <reason>"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  GlobalMessage: "%executor% &ahas warned %target%&a."
  ExecutorResponse: "&aYou have warned %player% &afor&f%reason%&a."
  TargetResponse: |-
    &cYou have been warned for&7%reason%&c.
    &4Please stop breaking the rules.

Mute:
  Permission: "vnitrogen.mute"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /mute <player> [-s] <reason>"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  PlayerIsMuted: "%server_prefix% &cPlayer is already muted!"
  GlobalMessage: "%executor% &ahas permanently muted %target%&a."
  ExecutorResponse: "&aYou have permanently muted %player% &afor&f%reason%&a."
  TargetResponse: |-
    &cYou have been permanently muted for&7%reason%&c.
    &4This mute will not expire.
  OnChatError: |-
    &cYou cannot talk as you are muted for&7%reason%&c.
    &4This mute will not expire.

TempMute:
  Permission: "vnitrogen.mute"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /tempmute <player> <time> [-s] <reason>"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  PlayerIsMuted: "%server_prefix% &cPlayer is already muted!"
  GlobalMessage: "%executor% &ahas temporarily muted %target%&a."
  ExecutorResponse: "&aYou have temporarily muted %player% &afor&f%reason%&a."
  TargetResponse: |-
    &cYou have been temporarily muted for&7%reason%&c.
    &cThis mute expires in: &7%expiry%&c.
  OnChatError: |-
    &cYou cannot talk as you are muted for&7%reason%&c.
    &cThis mute expires in: &7%expiry%&c.

Unmute:
  Permission: "vnitrogen.unmute"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /unmute <player> [-s]"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  PlayerIsNotMuted: "%server_prefix% &cPlayer is not muted!"
  GlobalMessage: "%executor% &ahas unmuted %target%&a."
  ExecutorResponse: "&aYou have unmuted %player%&a."
  TargetResponse: "&aYou have been unmuted."

Kick:
  Permission: "vnitrogen.kick"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /kick <player> [-s] <reason>"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  GlobalMessage: "%executor% &ahas kicked %target%&a."
  ExecutorResponse: "&aYou have kicked %player%&a for&f%reason%&a."
  KickMessage: |-
    &cYou have been &4kicked &cfrom the server.
    &7You were kicked for:&f%reason%&7.

Ban:
  Permission: "vnitrogen.ban"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /ban <player> [-s] <reason>"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  GlobalMessage: "%executor% &ahas permanently banned %target%&a."
  ExecutorResponse: "&aYou have permanently banned %player%&a for&f%reason%&a."
  BanMessage: |-
    &cYou have been &4banned &cfrom the server.
    &7You were banned for:&f%reason%&7.
    &4This ban will not expire.

TempBan:
  Permission: "vnitrogen.tempban"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /tempban <player> <time> [-s] <reason>"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  GlobalMessage: "%executor% &ahas temporarily banned %target%&a."
  ExecutorResponse: "&aYou have temporarily banned %player%&a for&f%reason%&a."
  BanMessage: |-
    &cYou have been &4banned &cfrom the server.
    &7You were banned for:&f%reason%&7.
    &cThis ban will expire on: &7%expiry%&c.

Unban:
  Permission: "vnitrogen.unban"
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /unban <player> [-s]"
  InvalidPlayer: "%server_prefix% &cInvalid Player."
  PlayerIsNotBanned: "%server_prefix% &cPlayer is not banned!"
  GlobalMessage: "%executor% &ahas unbanned %target%&a."
  ExecutorResponse: "&aYou have unbanned %player%&a."
