# vBasic v1.0 by Yochran
# https://github.com/Yochran

# One of the server cores for VectroMC
# https://vectromc.net

# Prefixes:

ServerPrefix: "&7[&6&lvScoreboard&7]"
PluginPrefix: "&7[&6&lvScoreboard&7]"

# Config Messages:

MustBePlayer: "%plugin_prefix% &cYou must be a player to use that command."
NoPermission: "%server_prefix% &cYou do not have permission to use that command."
ReloadMessage: "%plugin_prefix% &aYou have successfully reloaded the config.yml."
ReloadPermission: "vscoreboard.reload"

# Scoreboard:

  # Available Placeholders for the Scoreboard Format:
  #
  # %vanish% - player's vanish status
  # %onlinestaff% - all online staff
  # %online% - amount of online players (non vanished)
  # %rank% - player's rank
  # %name% - player's name
  # %world% - player's server
# %displayname% - player's display name (non-prefix)

Scoreboard:
  Enabled: true
  ToggleOffMessage: "&cYou have toggled off the scoreboard."
  ToggleOnMessage: "&aYou have toggled on the scoreboard."
  Global:
    Enabled: false
    Title: "&6&lvScoreboard"
    Format:
      - "&7&m----------------------&r"
      - "&6&lOnline:"
      - "&f %online%"
      - "&e "
      - "&6&lRank:"
      - "&f %rank%"
      - "&6 "
      - "&7vScoreboard v1.0"
      - "&7&m----------------------"
  Servers:
    hub-1:
      Enabled: true
      Title: "&6&lvScoreboard &7| Hub"
      Format:
        - "&7&m----------------------&r"
        - "&6&lOnline:"
        - "&f %online%"
        - "&e "
        - "&6&lRank:"
        - "&f %rank%"
        - "&6 "
        - "&7vScoreboard v1.0"
        - "&7&m----------------------"
    kitpvp:
      Enabled: true
      Title: "&6&lvScoreboard &7| KitPvP"
      Format:
        - "&7&m----------------------&r"
        - "&e * &f&lKills: &6N/A"
        - "&e * &f&lDeaths: &6N/A"
        - "&e * &f&lKDR: &6N/A"
        - "&e * &f&lMoney: &6N/A"
        - "&e * &f&lStreak: &6N/A &7(N/A)"
        - "&6 "
        - "&7vScoreboard v1.0"
        - "&7&m----------------------"
    soup:
      Enabled: true
      Title: "&6&lvScoreboard &7| Soup"
      Format:
        - "&7&m----------------------&r"
        - "&e * &f&lKills: &6N/A"
        - "&e * &f&lDeaths: &6N/A"
        - "&e * &f&lKDR: &6N/A"
        - "&e * &f&lMoney: &6N/A"
        - "&e * &f&lStreak: &6N/A &7(N/A)"
        - "&6 "
        - "&7vScoreboard v1.0"
        - "&7&m----------------------"
    survival:
      Enabled: true
      Title: "&6&lvScoreboard &7| Survival"
      Format:
        - "&7&m----------------------&r"
        - "&e * &f&lDeaths: &6N/A"
        - "&e * &f&lMoney: &6N/A"
        - "&e * &f&lRank: &6%rank%"
        - "&6 "
        - "&7vScoreboard v1.0"
        - "&7&m----------------------"

StaffScoreboard:
  Enabled: true
  Permission: "vscoreboard.staff"
  Title: "&6&lvScoreboard &7| ModMode"
  Format:
    - "&7&m----------------------&r"
    - "&e * &fVanish: %vanish%"
    - "&e * &fStaff Online: &6%onlinestaff%"
    - "&e * &fPlayers Online: &6%online%"
    - "&e * &fServer: &6%world%"
    - "&6 "
    - "&7vScoreboard v1.0"
    - "&7&m----------------------"
