# vScoreboard v1.0 by Yochran
# https://github.com/Yochran

# One of the server cores for VectroMC
# https://vectromc.net

# Prefixes:

ServerPrefix: "&7[&6&lvScoreboard&7]"
PluginPrefix: "&7[&6&lvScoreboard&7]"

# Config Messages:

MustBePlayer: "%plugin_prefix% &cYou must be a player to use that command."
NoPermission: "%server_prefix% &cYou do not have permission to use that command."
ReloadMessage: "%plugin_prefix% &aYou have successfully reloaded the config.yml."
ReloadPermission: "vscoreboard.reload"

# Scoreboard:

# Available Placeholders for the Scoreboard Format:
#
# %vanish% - player's vanish status
# %onlinestaff% - all online staff
# %online% - amount of online players (non vanished)
# %rank% - player's rank
# %name% - player's name
# %world% - player's server
# %displayname% - player's display name (non-prefix)
#
# Stats/Eco:
#
# %balance% - Balance of a user. (vBasic)
# %kills% - Kills of a user. (vBasic)
# %deaths% - Deaths of a user. (vBasic)
# %kdr% - KDR of a user. (vBasic)
# %streak% - Streak of a user. (vBasic)
# %bounty% - Get a user's bounty amount. (vBasic)

Scoreboard:
  Enabled: true
  ToggleOffMessage: "&cYou have toggled off the scoreboard."
  ToggleOnMessage: "&aYou have toggled on the scoreboard."
  Global:
    Enabled: false
    Title: "&6&lvScoreboard"
    Format:
      - "&7&m----------------------&r"
      - "&6&lOnline:"
      - "&f %online%"
      - "&e "
      - "&6&lRank:"
      - "&f %rank%"
      - "&6 "
      - "&7vScoreboard v1.0"
      - "&7&m----------------------"
  Servers:
    hub-1:
      Enabled: true
      Title: "&6&lvScoreboard &7| &6Hub"
      Format:
        - "&7&m----------------------&r"
        - "&6&lServer:"
        - "&e * &f&lOnline: &6%online%"
        - "&e "
        - "&6&lYou:"
        - "&e * &f&lRank: &6%rank%"
        - "&6 "
        - "&7vScoreboard v1.0"
        - "&7&m----------------------"
    kitpvp:
      Enabled: true
      Title: "&6&lvScoreboard &7| &aKitPvP"
      Format:
        - "&7&m----------------------&r"
        - "&a&lStats:"
        - "&a * &f&lKills: &2%kills%"
        - "&a * &f&lDeaths: &2%deaths%"
        - "&a * &f&lKDR: &2%kdr%"
        - "&a * &f&lMoney: &2$%balance%"
        - "&a * &f&lStreak: &2%streak%"
        - "&6 "
        - "&a&lYou:"
        - "&a * &f&lRank: &2%rank%"
        - "&a * &f&lBounty: &2%bounty%"
        - "&a "
        - "&7vScoreboard v1.0"
        - "&7&m----------------------"
    soup:
      Enabled: true
      Title: "&6&lvScoreboard &7| &3Soup"
      Format:
        - "&7&m----------------------&r"
        - "&3&lStats:"
        - "&b * &f&lKills: &3%kills%"
        - "&b * &f&lDeaths: &3%deaths%"
        - "&b * &f&lKDR: &3%kdr%"
        - "&b * &f&lMoney: &3$%balance%"
        - "&b * &f&lStreak: &3%streak%"
        - "&6 "
        - "&3&lYou:"
        - "&b * &f&lRank: &3%rank%"
        - "&b * &f&lBounty: &3%bounty%"
        - "&a "
        - "&7vScoreboard v1.0"
        - "&7&m----------------------"
    survival:
      Enabled: true
      Title: "&6&lvScoreboard &7| &5Survival"
      Format:
        - "&7&m----------------------&r"
        - "&5&lYou:"
        - "&d * &f&lMoney: &5$%balance%"
        - "&d * &f&lRank: &5%rank%"
        - "&6 "
        - "&5&lClaims:"
        - "&d * &f&lCurrent: &5N/A"
        - "&d * &f&lAmount: &5N/A"
        - "&5 "
        - "&7vScoreboard v1.0"
        - "&7&m----------------------"

StaffScoreboard:
  Enabled: true
  Permission: "vscoreboard.staff"
  Title: "&6&lvScoreboard &7| ModMode"
  Format:
    - "&7&m----------------------&r"
    - "&e * &f&lVanish: %vanish%"
    - "&e * &f&lStaff Online: &6%onlinestaff%"
    - "&e * &f&lPlayers Online: &6%online%"
    - "&e * &f&lServer: &6%world%"
    - "&6 "
    - "&7vScoreboard v1.0"
    - "&7&m----------------------"
