# vBasic v1.0 by Yochran
# https://github.com/Yochran

# One of the server cores for VectroMC
# https://vectromc.net

# Prefixes:

ServerPrefix: "&7[&6&lVectroMC&7]"
PluginPrefix: "&7[&6&lvScoreboard&7]"

# Config Messages:

MustBePlayer: "%plugin_prefix% &cYou must be a player to use that command."

# Scoreboard:

Scoreboard:
  Enabled: true
  ToggleOffMessage: "&cYou have toggled off the scoreboard."
  ToggleOnMessage: "&aYou have toggled on the scoreboard."

StaffScoreboard:
  Enabled: true
  Permission: "vscoreboard.staff"
