# vBasic v1.0 by Yochran
# https://github.com/Yochran

# One of the server cores for VectroMC
# https://vectromc.net

# Prefixes:

ServerPrefix: "&7[&6&lVectroMC&7]"
PluginPrefix: "&7[&6&lvScoreboard&7]"

# Config Messages:

MustBePlayer: "%plugin_prefix% &cYou must be a player to use that command."
NoPermission: "%server_prefix% &cYou do not have permission to use that command."
ReloadMessage: "%plugin_prefix% &aYou have successfully reloaded the config.yml."
ReloadPermission: "vscoreboard.reload"

# Scoreboard:

Scoreboard:
  Enabled: true
  ToggleOffMessage: "&cYou have toggled off the scoreboard."
  ToggleOnMessage: "&aYou have toggled on the scoreboard."
  Title: "&6&lVectroMC"
  # Available Placeholders:
  #
  # %online% - amount of online players (non vanished)
  # %rank% - player's rank
  # %name% - player's name
  # %displayname% - player's display name (non-prefix)
  Format:
    - "&7&m----------------------&r"
    - "&6&lOnline:"
    - "&f %online%"
    - "&e "
    - "&6&lRank:"
    - "&f %rank%"
    - "&6 "
    - "&7play.vectromc.net"
    - "&7&m----------------------"

StaffScoreboard:
  Enabled: true
  Permission: "vscoreboard.staff"
  Title: "&6&lVectroMC"
  # Available Placeholders:
  #
  # %vanish% - player's vanish status
  # %onlinestaff% - all online staff
  # %online% - amount of online players (non vanished)
  # %rank% - player's rank
  # %name% - player's name
  # %world% - player's server
  # %displayname% - player's display name (non-prefix)
  Format:
    - "&7&m----------------------&r"
    - "&e * &fVanish: %vanish%"
    - "&e * &fStaff Online: &6%onlinestaff%"
    - "&e * &fPlayers Online: &6%online%"
    - "&e * &fServer: &6%world%"
    - "&6 "
    - "&7play.vectromc.net"
    - "&7&m----------------------"
