# vBasic v1.0 by Yochran
# https://github.com/Yochran

# One of the server cores for VectroMC
# https://vectromc.net

# Prefixes:

PluginPrefix: "&7[&6&lvStaffUtils&7]"
ServerPrefix: "&7[&6&lVectroMC&7]"

# Permissions:

VanishPermission: "vstaffutils.vanish"
VanishOthersPermission: "vstaffutils.vanish.others"

ModmodePermission: "vstaffutils.modmode"
ModmodeOthersPermission: "vstaffutils.modmode.others"

BuildModePermission: "vstaffutils.buildmode"

FreezePermission: "vstaffutils.freeze"

ReportNotifyPermission: "vstaffutils.reports.notify"

OnlineStaffPermission: "vstaffutils.staff"

# Config Messages:

MustBePlayer: "%plugin_prefix% &cYou must be a player to use that command."
NoPermission: "%server_prefix% &cYou do not have permission to use that command."
ReloadConfig: "%plugin_prefix% &aYou have successfully reloaded the config.yml."

# Below is everything regarding Vanish:

VanishOnSelf: "&eYou are now &6Vanished&e."
VanishOffSelf: "&eYou are no longer &6Vanished&e."

VanishOnOther: "&eYou have &6Vanished %target%&e."
VanishOffOther: "&eYou have &6UnVanished %target%&e."

VanishLogin: "&6&lYou logged out while in vanish, so you have been kept in vanish."

# Below is everything regarding buildmode:

BuildOn: "&eYou have turned on &6Build Mode&e."
BuildOff: "&eYou have turned off &6Build Mode&e."

BuildErrorMessage: "&cYou cannot build as your buildmode is disabled."

# Below is everything regarding modmode:

ModmodeIncorrectUsage: "%server_prefix% &cIncorrect Usage! /modmode [player]"
ModmodeInvalidPlayer: "%server_prefix% &cInvalid Player!"

ModmodeOnSelf: "&eYou have enabled your &6Modmode&e."
ModmodeOffSelf: "&eYou have disabled your &6Modmode&e."

ModmodeOnOthers: "&eYou have enabled %target%&e's &6Modmode&e."
ModmodeOffOthers: "&eYou have disabled %target%&e's &6Modmode&e."

ModmodeBuildErrorMessage: "&cYou cannot build as you are in modmode."

# Below is everything relating to freeze:

FreezeIncorrectUsage: "%server_prefix% &cIncorrect Usage! /freeze <player>"
FreezeInvalidPlayer: "%server_prefix% &cInvalid Player%"

FreezeOnCooldown: "%server_prefix% &cYou are on cooldown for that!"

FreezeOn: "&eYou have frozen %target%&e."
FreezeOff: "&eYou have unfrozen %target%&e."

FreezeOffPlayer: "&eYou have been unfrozen."

FreezePopup: |-
  &7&m---------------------------------------
  &4&lYou have been frozen!
  &cIf you logout, you will be &4banned&c!
  &c
  &6Please join the discord at: &b&n<discord link here>
  &7&m---------------------------------------

# Below is everything regarding reports:

ReportIncorrectUsage: "%server_prefix% &cIncorrect Usage! /report <player>"
ReportInvalidPlayer: "%server_prefix% &cInvalid Player!"
ReportFormat:
  PlayerFormat: "&eYou have reported %target% &efor &f%reason%&e."
  StaffFormat: "&b[S] &3[%world%] %player% &3has reported %target% &3for &b%reason%"

# Below is everything regarding staff alerts:

StaffAlerts:
  VanishOnSelf: "&7&o[%player% &7&ohas vanished&7&o]"
  VanishOffSelf: "&7&o[%player% &7&ohas unvanished&7&o]"
  VanishOnOther: "&7&o[%player% &7&ohas vanished %target%&7&o]"
  VanishOffOther: "&7&o[%player% &7&ohas unvanished %target%&7&o]"
  BuildOn: "&7&o[%player% &7&ohas toggled on buildmode]"
  BuildOff: "&7&o[%player% &7&ohas toggled off buildmode]"
  ModmodeOnSelf: "&7&o[%player% &7&ohas entered modmode&7&o]"
  ModmodeOffSelf: "&7&o[%player% &7&ohas exited modmode&7&o]"
  ModmodeOnOthers: "&7&o[%player% &7&ohas put %target% &7&oin modmode&7&o]"
  ModmodeOffOthers: "&7&o[%player% &7&ohas put %target% &7&oout of modmode&7&o]"
  FreezeOn: "&7&o[%player% &7&ohas frozen %target%&7&o]"
  FreezeOff: "&7&o[%player% &7&ohas unfrozen %target%&7&o]"