# vNitrogen v1.0 by Yochran
# https://github.com/Yochran

# One of the server cores for VectroMC
# https://vectromc.net

# Prefixes:

PluginPrefix: "&7[&6&lvNitrogen&7]"
ServerPrefix: "&7[&6&lVectroMC&7]"

# Ranks:

Owner:
  prefix: "&7(&4Owner&7) &4"
  color: "&4"
Developer:
  prefix: "&7(&6&oDeveloper&7) &6&o"
  color: "&6&o"
Manager:
  prefix: "&7(&9Manager&7) &9"
  color: "&9"
Admin:
  prefix: "&7(&cAdmin&7) &c"
  color: "&c"
Senior-Mod:
  prefix: "&7(&5&oSenior-Mod&7) &5&o"
  color: "&5&o"
Mod:
  prefix: "&7(&5Mod&7) &5"
  color: "&5"
Trial-Mod:
  prefix: "&7(&eTrial-Mod&7) &e"
  color: "&e"
Builder:
  prefix: "&7(&2Builder&7) &2"
  color: "&2"
Default:
  prefix: "&7"
  color: "&7"

# Config Messages:

YouMustBePlayer: "%plugin_prefix% &cYou must be a player to use that command."
NoPermission: "%server_prefix% &cYou do not have permission to use that command."
CantFindPlayer: "%server_prefix% &cThat player was not found."
ReloadConfig: "%plugin_prefix% &aYou have successfully reloaded the config.yml."

# Everything regarding to the /setrank command:

Setrank:
  IncorrectUsage: "%server_prefix% &cIncorrect Usage! /setrank <player> <rank>"
  InvalidRank: "%server_prefix% &cInvalid Rank!"
  # You cannot use %server_prefix% or %plugin_prefix% for these messages below!
  SenderSetRank: "&aYou have set %target%&a's rank to %rank%&a."
  TargetSetRank: "&aYour rank has been set to %rank%&a."

# Everything regarding the different staff chats:

BuildChat:
  permission: "vnitrogen.chats.build"
  format: "&2[B] &3[%world%] %player%&7: &b%message%"
  incorrectusage: "%server_prefix% &cIncorrect Usage! /bc <message>"
  Toggles:
    ToggleOn: "&2[B] &3You have toggled on &2Build &3chat."
    ToggleOff: "&2[B] &3You have toggled off &2Build &3chat."

StaffChat:
  permission: "vnitrogen.chats.staff"
  format: "&b[S] &3[%world%] %player%&7: &b%message%"
  incorrectusage: "%server_prefix% &cIncorrect Usage! /sc <message>"
  Toggles:
    ToggleOn: "&b[S] &3You have toggled on &bStaff &3chat."
    ToggleOff: "&b[S] &3You have toggled off &bStaff &3chat."

AdminChat:
  permission: "vnitrogen.chats.admin"
  format: "&c[A] &3[%world%] %player%&7: &b%message%"
  incorrectusage: "%server_prefix% &cIncorrect Usage! /ac <message>"
  Toggles:
    ToggleOn: "&c[A] &3You have toggled on &cAdmin &3chat."
    ToggleOff: "&c[A] &3You have toggled off &cAdmin &3chat."

ManagementChat:
  permission: "vnitrogen.chats.management"
  format: "&4[M] &3[%world%] %player%&7: &b%message%"
  incorrectusage: "%server_prefix% &cIncorrect Usage! /mc <message>"
  Toggles:
    ToggleOn: "&4[M] &3You have toggled on &4Management &3chat."
    ToggleOff: "&4[M] &3You have toggled off &4Management &3chat."

# Below is everything regarding staff log messages:

StaffLogin:
  format: "&b[S] %player% &3connected to &b%world%"
  permission: "vnitrogen.staff.log"
  notifypermission: "vnitrogen.notify"
StaffLogout:
  format: "&b[S] %player% &3disconnected from &b%world%"
  permission: "vnitrogen.staff.log"
  notifypermission: "vnitrogen.notify"
StaffWorldChange:
  format: "&b[S] %player% &3connected to &b%newWorld% &3from &b%oldWorld%"
  permission: "vnitrogen.staff.log"
  notifypermission: "vnitrogen.notify"