name: vNitrogen
version: ${project.version}
main: net.vectromc.vnitrogen.vNitrogen
api-version: 1.16
authors: [Yochran]
description: One of the server cores for VectroMC
website: https://vectromc.net
commands:
  vNitrogen:
    description: Gets the plugin information.
    usage: /<command>
    aliases: nitrogen
  Setrank:
    description: Set a users rank.
    usage: /<command>
    aliases: rankset
  BuildChat:
    description: Talk to all online builders.
    usage: /<command>
    aliases: [bldc, buildc, bchat]
  StaffChat:
    description: Talk to all online staff.
    usage: /<command>
    aliases: [sc, staffc, schat]
  AdminChat:
    description: Talk to all online admins.
    usage: /<command>
    aliases: [ac, adminc, achat]
  ManagementChat:
    description: Talk to all online managers and above.
    usage: /<command>
    aliases: [mc, managementc, mchat]
  BuildChatToggle:
    description: Toggle on or off build chat.
    usage: /<command>
    aliases: [tbc, bct]
  StaffChatToggle:
    description: Toggle on or off staff chat.
    usage: /<command>
    aliases: [tsc, sct]
  AdminChatToggle:
    description: Toggle on or off admin chat.
    usage: /<command>
    aliases: [tac, act]
  ManagementChatToggle:
    description: Toggle on or off management chat.
    usage: /<command>
    aliases: [tmc, mct]
